#!/usr/bin/env python3
"""Import verified optimization traces into a self-contained local corpus.

The input tree is read only. All persisted locators point at KernelWiki-owned
files, and every generated byte is deterministic for identical input.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import os
import re
import shutil
import tempfile
from collections import Counter, defaultdict
from pathlib import Path, PurePosixPath

import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _yaml_compat import yaml  # noqa: E402


REPO_ROOT = Path(__file__).resolve().parent.parent
LEDGER_PATH = Path("data/trace-import-ledger.jsonl")
RECEIPT_DATE_POLICY = "evidence-preserved-unknown"

EXTERNAL_LOCATOR_RE = re.compile(
    r"(?i)(?:/workspace/|sessions-(?:codex|claude)/|"
    r"(?:^|[\s`\"'])repo/(?:solution|profiles|scripts|benchmarks)/)"
)
TRACE_LOCATOR_RE = re.compile(
    r"(?i)(?:/workspace/|sessions-(?:codex|claude)/|"
    r"(?:^|[\s`\"'])(?:repo|solution|profiles?|scripts|bench_results|benchmarks)/)"
)
KNOWN_CONTAMINATION = (
    "For memory-bound kernels (low arithmetic intensity)",
    "Decompression Engine",
)
SUPPORTED_CODE_SUFFIXES = {
    ".py", ".cu", ".cuh", ".cpp", ".cc", ".cxx", ".h", ".hpp", ".ptx",
}

TECHNIQUE_MAP = {
    "precision or data-type specialization": "precision-specialization",
    "tiling / blocking": "tile-scheduling",
    "shared-memory reuse": "shared-memory-optimization",
    "software pipelining and asynchronous execution": "pipeline-stages",
    "TMEM / Tensor Core paths": "tensor-core-optimization",
    "operator fusion": "kernel-fusion",
    "caching and prefetching": "cache-policy",
    "TMA asynchronous transfers": "tma-transfers",
    "parallel reduction": "parallel-reduction",
    "vectorized memory access": "vectorized-loads",
    "persistent-kernel scheduling": "persistent-kernel",
    "warp specialization": "warp-specialization",
}

FAMILY_LABELS = {
    "comba_forward": "Comba forward",
    "cuda_cpp": "CUDA C++ Gated Delta Net prefill",
    "cute": "CuTe MoE",
    "dense_kernel_01_sm100": "SM100 block-scaled dense GEMM",
    "dense_kernel_11_flashattention_3": "FlashAttention 3 forward",
    "dense_kernel_12_flashattention_3": "FlashAttention 3 backward",
    "dsa_attention": "DeepSeek sparse attention",
    "gated_delta_product_forward": "gated delta product forward",
    "gated_oja_forward": "gated Oja forward",
    "gdn2_forward": "GDN2 forward",
    "gdn_prefill": "Gated Delta Net prefill",
    "gsa_forward": "Gated Slot Attention forward",
    "iplr_forward": "IPLR forward",
    "kda_backward": "KDA backward",
    "kda_forward": "KDA forward",
    "mesa_net_forward": "MesaNet forward",
    "moe": "Mixture-of-Experts",
}

FAMILY_KERNEL_TYPES = {
    "comba_forward": ["linear-attention", "prefill"],
    "cuda_cpp": ["gated-delta-net", "linear-attention", "prefill"],
    "cute": ["moe", "grouped-gemm"],
    "dense_kernel_01_sm100": ["gemm"],
    "dense_kernel_11_flashattention_3": ["attention", "flash-attention"],
    "dense_kernel_12_flashattention_3": ["attention", "flash-attention"],
    "dsa_attention": ["attention", "sparse-attention", "mla", "decode"],
    "gated_delta_product_forward": ["linear-attention", "prefill"],
    "gated_oja_forward": ["linear-attention", "prefill"],
    "gdn2_forward": ["gated-delta-net", "linear-attention", "prefill"],
    "gdn_prefill": ["gated-delta-net", "linear-attention", "prefill"],
    "gsa_forward": ["attention", "linear-attention", "prefill"],
    "iplr_forward": ["linear-attention", "prefill"],
    "kda_backward": ["linear-attention"],
    "kda_forward": ["linear-attention", "prefill"],
    "mesa_net_forward": ["linear-attention", "prefill"],
    "moe": ["moe", "grouped-gemm"],
}

RELATED_BY_KERNEL_TYPE = {
    "moe": "kernel-fused-moe",
    "grouped-gemm": "kernel-grouped-gemm",
    "gated-delta-net": "kernel-gated-delta-net",
    "sparse-attention": "kernel-sparse-mla",
    "mla": "kernel-flashmla",
    "flash-attention": "kernel-flash-attention-4",
    "gemm": "kernel-deepgemm",
}

TECHNIQUE_RELATED = {
    "tile-scheduling": "technique-tile-scheduling",
    "shared-memory-optimization": "pattern-memory-bound",
    "pipeline-stages": "technique-pipeline-stages",
    "kernel-fusion": "technique-kernel-fusion",
    "cache-policy": "technique-cache-policy",
    "vectorized-loads": "technique-vectorized-loads",
    "persistent-kernel": "technique-persistent-kernels",
    "warp-specialization": "technique-warp-specialization",
}


class ImportFailure(RuntimeError):
    """An input-contract or output-ownership failure."""


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def canonical_json(value) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def normalized_text(raw: bytes) -> tuple[str, str]:
    text = raw.decode("utf-8")
    mode = "copied-verbatim"
    if "\r" in text:
        text = text.replace("\r\n", "\n").replace("\r", "\n")
        mode = "newline-normalized"
    return text, mode


def yaml_text(value) -> str:
    return yaml.safe_dump(
        value,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=1000,
    )


def frontmatter(value) -> str:
    return f"---\n{yaml_text(value)}---\n\n"


def section(text: str, heading: str) -> str | None:
    match = re.search(rf"^## {re.escape(heading)}\s*$", text, re.MULTILINE)
    if not match:
        return None
    start = match.end()
    end = re.search(r"^## ", text[start:], re.MULTILINE)
    return text[start : start + (end.start() if end else len(text) - start)]


def fenced_section(text: str, heading: str) -> tuple[str | None, str | None]:
    block = section(text, heading)
    if block is None:
        return None, None
    match = re.search(r"^```([^\n]*)\n(.*?)^```\s*$", block, re.MULTILINE | re.DOTALL)
    if not match:
        return None, None
    return match.group(1).strip(), match.group(2)


def task_section(text: str) -> str | None:
    task = section(text, "Task")
    if task is None:
        return None
    # The task may contain level-two headings; section() therefore stops early.
    # Parse from the original document through the enclosing details block.
    start = re.search(r"^## Task\s*$", text, re.MULTILINE)
    if not start:
        return None
    tail = text[start.end() :]
    match = re.search(
        r"^(?P<fence>`{3,})markdown\n(.*?)^(?P=fence)\n\s*</details>",
        tail,
        re.MULTILINE | re.DOTALL,
    )
    return match.group(2) if match else None


def parse_metadata(text: str) -> dict[str, str]:
    block = section(text, "Metadata") or ""
    metadata = {}
    for line in block.splitlines():
        match = re.match(r"^\|\s*([^|]+?)\s*\|\s*(.*?)\s*\|$", line)
        if not match or match.group(1).strip() in {"Field", "---"}:
            continue
        value = match.group(2).strip()
        if value.startswith("`") and value.endswith("`"):
            value = value[1:-1]
        metadata[match.group(1).strip()] = value
    return metadata


def trim_diff(value: str) -> list[str]:
    lines = value.splitlines()
    while lines and not lines[-1].strip():
        lines.pop()
    return lines


def generated_diff(
    before: str,
    after: str,
    logical_name: str | None = None,
    *,
    before_name: str | None = None,
    after_name: str | None = None,
) -> str:
    before_lines = before.splitlines(keepends=True)
    after_lines = after.splitlines(keepends=True)
    diff = "".join(
        difflib.unified_diff(
            before_lines,
            after_lines,
            fromfile=before_name or f"before/{logical_name}",
            tofile=after_name or f"after/{logical_name}",
        )
    )
    if diff and not diff.endswith("\n"):
        diff += "\n"
    return diff


def number_present(text: str, value: str) -> bool:
    expected = float(value)
    return any(
        abs(float(candidate) - expected) <= max(1e-12, abs(expected) * 1e-12)
        for candidate in re.findall(r"(?<![0-9.])([0-9]+(?:\.[0-9]+)?)(?![0-9.])", text)
    )


def clean_excerpt(trace: str) -> str | None:
    trace = trace.strip()
    table = trace.find(r"\|")
    if table >= 0:
        trace = trace[table:]
    else:
        trace = re.sub(r"^[^\s]+/[^:]+:\d+:\s*", "", trace)
    if TRACE_LOCATOR_RE.search(trace):
        return None
    return trace if trace else None


def _percent(interp: str) -> float | None:
    match = re.search(r"([0-9]+(?:\.[0-9]+)?)%", interp)
    return float(match.group(1)) if match else None


def parse_comparison(heading: str, interp: str, trace: str) -> dict | None:
    if any(marker in trace for marker in KNOWN_CONTAMINATION):
        return None
    lowered = trace.lower()
    if (
        "regress" in lowered
        or "falsifying" in lowered
        or "no code change lands" in lowered
        or "sibling" in lowered
        or "despite" in lowered
        or re.search(r"all-workload geomean was\s+0\.", lowered)
    ):
        return None
    excerpt = clean_excerpt(trace)
    if not excerpt:
        return None

    metric = None
    unit = None
    before = None
    after = None

    latency = re.search(
        r"Latency decreases from\s+([0-9]+(?:\.[0-9]+)?)\s*([uµ]?s|ms|s)\s+"
        r"to\s+([0-9]+(?:\.[0-9]+)?)\s*([uµ]?s|ms|s)",
        interp,
        re.IGNORECASE,
    )
    if latency:
        before, unit, after, after_unit = latency.groups()
        if unit.replace("µ", "u").lower() != after_unit.replace("µ", "u").lower():
            return None
        metric = "latency"
    else:
        score = re.search(
            r"performance metric increases from\s+([0-9]+(?:\.[0-9]+)?)\s+to\s+"
            r"([0-9]+(?:\.[0-9]+)?)",
            interp,
            re.IGNORECASE,
        )
        if score:
            before, after = score.groups()
            metric, unit = "score", "ratio"

    if before is None and "inherited-to-selected" in interp.lower():
        values = re.findall(r"([0-9]+(?:\.[0-9]+)?)\s*([uµ]?s|ms|s)\b", excerpt)
        target_percent = _percent(interp)
        candidates = []
        for left_index, (left, left_unit) in enumerate(values):
            for right, right_unit in values[left_index + 1 :]:
                if left_unit.replace("µ", "u").lower() != right_unit.replace("µ", "u").lower():
                    continue
                left_value, right_value = float(left), float(right)
                if left_value <= right_value:
                    continue
                actual_percent = (left_value - right_value) / left_value * 100
                error = abs(actual_percent - target_percent) if target_percent is not None else 0
                candidates.append((error, left, right, left_unit))
        if candidates:
            error, before, after, unit = min(candidates, key=lambda value: value[0])
            if target_percent is None or error <= max(0.08, target_percent * 0.08):
                metric = "latency"
            else:
                before = after = unit = None

    if before is None:
        old_new = re.search(
            r"old\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*([uµ]?s|ms|s).*?"
            r"new\s*=\s*([0-9]+(?:\.[0-9]+)?)\s*([uµ]?s|ms|s)",
            excerpt,
            re.IGNORECASE,
        )
        if old_new:
            before, unit, after, after_unit = old_new.groups()
            if unit.replace("µ", "u").lower() != after_unit.replace("µ", "u").lower():
                return None
            metric = "latency"

    if before is None:
        return None
    if not number_present(excerpt, before) or not number_present(excerpt, after):
        return None

    before_value = float(before)
    after_value = float(after)
    if metric == "latency" and not before_value > after_value:
        return None
    if metric == "score" and not after_value > before_value:
        return None
    ratio = before_value / after_value if metric == "latency" else after_value / before_value
    if ratio <= 1 or ratio > 20:
        return None
    return {
        "heading": heading,
        "metric": metric,
        "unit": unit.replace("µ", "u"),
        "before_value": before_value,
        "after_value": after_value,
        "value": after_value,
        "improvement_percent": _percent(interp),
        "interpretation": interp.strip(),
        "excerpt": excerpt,
    }


def parse_performance(text: str) -> tuple[list[dict], int]:
    block = section(text, "Verified performance evidence")
    if block is None:
        return [], 0
    entries = []
    raw_count = 0
    pattern = re.compile(r"^###\s+(.+?)\s*$\n(.*?)(?=^###\s+|\Z)", re.MULTILINE | re.DOTALL)
    for match in pattern.finditer(block):
        raw_count += 1
        entry = match.group(2)
        interp_match = re.search(r"^- Interpretation:\s*(.+)$", entry, re.MULTILINE)
        trace_match = re.search(r"^- Trace text:\s*(.+)$", entry, re.MULTILINE)
        if not interp_match or not trace_match:
            continue
        parsed = parse_comparison(match.group(1), interp_match.group(1), trace_match.group(1))
        if parsed:
            entries.append(parsed)
    return entries, raw_count


def detect_architectures(title: str) -> list[str]:
    value = title.lower()
    if "b300" in value or "sm103" in value:
        return ["sm103"]
    if "b200" in value or "sm100" in value:
        return ["sm100"]
    if "hopper" in value or "h100" in value or "sm90" in value:
        return ["sm90"]
    if "blackwell" in value:
        return ["blackwell"]
    return []


def detect_languages(title: str, code: str) -> list[str]:
    value = f"{title}\n{code}".lower()
    if "triton" in title.lower():
        return ["triton"]
    if "cuda c++" in title.lower() or "cuda-c++" in title.lower():
        return ["cuda-cpp"]
    if "cute-dsl" in title.lower() or "cutlass.cute" in value or "import cute" in value:
        return ["cute-dsl"]
    if "triton" in value and "@triton" in value:
        return ["triton"]
    return ["python"]


def detect_dtype(title: str, task: str) -> str:
    value = f"{title}\n{task}".lower()
    found = []
    for token in ("fp8", "fp4", "bf16", "fp16", "float32"):
        if token in value:
            found.append(token)
    return "/".join(found[:2]) if found else "not stated"


def detect_hardware(text: str) -> list[str]:
    lower = text.lower()
    patterns = {
        "tcgen05": r"tcgen05",
        "tmem": r"\btmem\b|tensor memory",
        "tma": r"\btma\b|tensor memory accelerator",
        "wgmma": r"\bwgmma\b",
        "nvfp4": r"\bnvfp4\b",
        "fp8": r"\bfp8\b",
        "fp4": r"\bfp4\b",
        "mbarrier": r"\bmbarrier\b",
        "ldmatrix": r"\bldmatrix\b",
        "stmatrix": r"\bstmatrix\b",
        "2sm-cooperative": r"\b2[- ]sm\b|two[- ]sm|cta_group::2",
        "pdl": r"programmatic dependent launch|\bpdl\b",
    }
    return [name for name, pattern in patterns.items() if re.search(pattern, lower)]


def gpu_label(architectures: list[str]) -> str:
    return {
        "sm103": "B300",
        "sm100": "B200",
        "sm90": "Hopper GPU (exact model not stated)",
        "blackwell": "Blackwell GPU (exact model not stated)",
    }.get(architectures[0] if architectures else "", "not stated")


def sanitize_task(task: str, title: str, family: str) -> str:
    """Keep the English task record while removing stale workspace locators."""
    task = task.replace("\r\n", "\n").replace("\r", "\n")
    task = re.sub(r"(?m)^\s{4}(?:gpu-run|bash|python3?).*$", "    [Original benchmark command omitted.]", task)

    def code_span(match):
        value = match.group(1)
        if re.search(
            r"(?i)(?:^/|(?:^|/)(?:repo|solution|profiles?|scripts|bench_results|benchmarks)(?:/|$)|"
            r"\.(?:py|md|csv|jsonl|sh):\d+$)",
            value,
        ):
            return "`[original task locator omitted]`"
        return match.group(0)

    task = re.sub(r"`([^`]+)`", code_span, task)
    task = re.sub(
        r"(?i)(?:/workspace/[^\s),;]+|(?:repo|solution|profiles?|scripts|bench_results|benchmarks)/[^\s),;]+)",
        "[original workspace locator omitted]",
        task,
    )
    task = re.sub(
        r"(?i)\b(?:repo|solution|profiles?|scripts|bench_results|benchmarks)/",
        "[original workspace locator omitted]",
        task,
    )
    task = re.sub(r"\n{3,}", "\n\n", task).strip() + "\n"
    header = (
        "<!-- Local transcription: operational source-workspace locators were omitted. -->\n"
        f"<!-- Task family: {family}; original English title: {title} -->\n\n"
    )
    return header + task


def correctness_record(task: str, performance_block: str) -> tuple[str, str]:
    explicit_patterns = (
        r"[^.\n]*(?:\d+/\d+ workloads pass correctness|all workloads pass(?:ing)? correctness|"
        r"correctness green)[^.\n]*[.]?",
    )
    for pattern in explicit_patterns:
        match = re.search(pattern, performance_block, re.IGNORECASE)
        if match:
            excerpt = clean_excerpt(match.group(0).strip())
            if excerpt:
                return "explicit-pass", excerpt
    gate = re.search(r"[^.\n]*correctness[^.\n]*[.]?", task, re.IGNORECASE)
    if gate:
        value = sanitize_task(gate.group(0).strip(), "correctness gate", "local").split("\n\n", 1)[-1].strip()
        return "gate-described-no-explicit-result", value
    return "", ""


def parse_evidence(row: dict, raw: bytes) -> tuple[dict | None, str | None]:
    try:
        text, evidence_mode = normalized_text(raw)
    except UnicodeDecodeError:
        return None, "evidence_not_utf8"
    metadata = parse_metadata(text)
    if metadata.get("Task family") != row.get("task_family"):
        return None, "manifest_metadata_task_family_mismatch"
    if metadata.get("Run") != row.get("run_path"):
        return None, "manifest_metadata_run_mismatch"
    if metadata.get("Compared source file") != row.get("selected_code_path"):
        return None, "manifest_metadata_code_path_mismatch"

    task = task_section(text)
    before_lang, before = fenced_section(text, "Complete code before optimization")
    after_lang, after = fenced_section(text, "Complete code after optimization")
    _diff_lang, imported_diff = fenced_section(text, "Complete unified diff")
    if None in (task, before, after, imported_diff):
        return None, "missing_required_evidence_section"
    if not before.strip():
        return None, "empty_before_source"
    if not after.strip():
        return None, "empty_after_source"
    if before == after:
        return None, "identical_before_after_source"
    if TRACE_LOCATOR_RE.search(before) or TRACE_LOCATOR_RE.search(after):
        return None, "source_contains_external_locator"

    title_match = re.match(r"^# Verified Optimization Evidence:\s*(.+)$", text)
    title = title_match.group(1).strip() if title_match else str(row.get("title", "")).strip()
    if title != row.get("title"):
        return None, "manifest_evidence_title_mismatch"
    if any(ord(character) > 127 for character in title):
        return None, "non_english_canonical_task"
    if row.get("task_family") == "cuda_cpp" and re.search(r"CuTe-DSL only|entirely in CuTe", task, re.IGNORECASE):
        if re.search(r"torch\.utils\.cpp_extension|\.cu[\"']", before + after):
            return None, "language_evidence_inconsistent"

    logical_name = Path(str(row["selected_code_path"])).name
    code_suffix = Path(logical_name).suffix.lower()
    if code_suffix not in SUPPORTED_CODE_SUFFIXES:
        return None, "unsupported_code_suffix"
    before_name = f"before{code_suffix}"
    after_name = f"after{code_suffix}"
    imported_expected = generated_diff(before, after, str(row["selected_code_path"]))
    if trim_diff(imported_diff) != trim_diff(imported_expected):
        return None, "imported_diff_inconsistent"
    local_diff = generated_diff(before, after, before_name=before_name, after_name=after_name)

    comparisons, raw_comparison_count = parse_performance(text)
    if not comparisons:
        return None, "no_direct_before_after_comparison"

    architectures = detect_architectures(f"{title}\n{task}")
    if not architectures:
        return None, "architecture_not_explicit"
    languages = detect_languages(title, before + after)
    if not languages:
        return None, "language_not_explicit"

    performance_block = section(text, "Verified performance evidence") or ""
    correctness_status, correctness_detail = correctness_record(task, performance_block)
    if not correctness_status:
        return None, "missing_correctness_gate"

    techniques = []
    for item in row.get("techniques") or []:
        mapped = TECHNIQUE_MAP.get(item)
        if not mapped:
            return None, "unmapped_technique"
        if mapped not in techniques:
            techniques.append(mapped)

    family = row["task_family"]
    kernel_types = FAMILY_KERNEL_TYPES.get(family)
    if not kernel_types:
        return None, "unmapped_task_family"
    hardware = detect_hardware(f"{task}\n{before}\n{after}")
    task_local = sanitize_task(task, title, family)
    if TRACE_LOCATOR_RE.search(task_local):
        return None, "task_locator_sanitization_failed"

    why = section(text, "Why the optimized version is faster") or ""
    observed = []
    for line in why.splitlines():
        match = re.match(r"^- \*\*Code change:\*\*\s*(.+)$", line)
        if match and not TRACE_LOCATOR_RE.search(match.group(1)):
            observed.append(match.group(1).strip())

    return {
        "text": text,
        "evidence_mode": evidence_mode,
        "evidence_sha256": sha256_bytes(text.encode("utf-8")),
        "task": task_local,
        "before": before,
        "after": after,
        "diff": local_diff,
        "language_fence": before_lang or after_lang or "python",
        "title": title,
        "architectures": architectures,
        "languages": languages,
        "dtype": detect_dtype(title, task),
        "techniques": techniques,
        "hardware_features": hardware,
        "kernel_types": kernel_types,
        "comparisons": comparisons,
        "raw_comparison_count": raw_comparison_count,
        "correctness_status": correctness_status,
        "correctness_detail": correctness_detail,
        "observed_changes": observed,
        "logical_code_name": logical_name,
        "before_name": before_name,
        "after_name": after_name,
    }, None


def logical_ids(row: dict, parsed: dict, manifest_sha: str) -> tuple[str, str]:
    run_sha = sha256_bytes(str(row["run_path"]).encode("utf-8"))[:16]
    logical_run_id = f"run-{run_sha}"
    identity = "\0".join(
        [
            row["task_family"],
            logical_run_id,
            row["selected_code_path"],
            parsed["evidence_sha256"],
        ]
    )
    suffix = sha256_bytes(identity.encode("utf-8"))[:16]
    experiment_id = f"experiment-{row['task_family'].replace('_', '-')}-{suffix}"
    return logical_run_id, experiment_id


def family_page_ids(family: str) -> tuple[str, str]:
    """Return human-facing aggregate IDs while bundles retain hashed identity."""
    slug = family.replace("_", "-")
    return f"experiment-family-{slug}", f"kernel-trace-{slug}"


def evidence_limitations(row: dict, parsed: dict) -> list[str]:
    limitations = [
        "The local corpus preserves the selected comparison, not the complete session trace.",
        "Causal mechanisms are hypotheses unless explicitly attributed by the retained evidence.",
    ]
    if parsed["correctness_status"] == "gate-described-no-explicit-result":
        limitations.append(
            "The retained comparison has no separate correctness result; the applicable task gate is documented."
        )
    if row.get("unreplayed_mutations"):
        limitations.append(
            f"The manifest reports {int(row['unreplayed_mutations'])} unreplayed mutation(s) outside the selected complete source pair."
        )
    if parsed["raw_comparison_count"] > len(parsed["comparisons"]):
        limitations.append(
            "Performance snippets that did not prove a direct positive old-to-new comparison were omitted."
        )
    return limitations


def performance_markdown(parsed: dict) -> str:
    lines = [
        "# Performance and correctness evidence",
        "",
        "The quotations below are exact retained trace substrings. Source-session filesystem locators were not retained.",
        "Analysis is labeled separately and does not claim a stronger result than the quotation.",
        "",
    ]
    for index, comparison in enumerate(parsed["comparisons"], 1):
        lines.extend(
            [
                f"## Comparison {index}",
                "",
                "### Exact retained excerpt",
                "",
                "```text",
                comparison["excerpt"],
                "```",
                "",
                "### English interpretation",
                "",
                comparison["interpretation"],
                "",
                f"Structured result: `{comparison['metric']}` changed from "
                f"`{comparison['before_value']} {comparison['unit']}` to "
                f"`{comparison['after_value']} {comparison['unit']}`.",
                "",
            ]
        )
    lines.extend(
        [
            "## Correctness",
            "",
            f"Status: `{parsed['correctness_status']}`.",
            "",
            parsed["correctness_detail"],
            "",
        ]
    )
    return "\n".join(lines)


def performance_claims(
    parsed: dict,
    source_id: str,
    artifact_dir: str,
    experiment_id: str | None = None,
) -> list[dict]:
    claims = []
    for index, comparison in enumerate(parsed["comparisons"], 1):
        claim = {
                "gpu": gpu_label(parsed["architectures"]),
                "dtype": parsed["dtype"],
                "shape": "not stated in the retained comparison",
                "metric": comparison["metric"],
                "value": comparison["value"],
                "before_value": comparison["before_value"],
                "after_value": comparison["after_value"],
                "unit": comparison["unit"],
                "source_id": source_id,
                "source_locator": f"{artifact_dir}/performance.md#comparison-{index}",
            }
        if experiment_id:
            claim["experiment_id"] = experiment_id
        claims.append(claim)
    return claims


def related_ids(parsed: dict) -> list[str]:
    result = []
    for kernel_type in parsed["kernel_types"]:
        candidate = RELATED_BY_KERNEL_TYPE.get(kernel_type)
        if candidate and candidate not in result:
            result.append(candidate)
    for technique in parsed["techniques"]:
        candidate = TECHNIQUE_RELATED.get(technique)
        if candidate and candidate not in result:
            result.append(candidate)
    for language in parsed["languages"]:
        candidate = {
            "cute-dsl": "lang-cute-dsl",
            "triton": "lang-triton",
            "cuda-cpp": "lang-cuda-cpp",
            "ptx": "lang-ptx",
        }.get(language)
        if candidate and candidate not in result:
            result.append(candidate)
    for feature in parsed["hardware_features"]:
        candidate = {
            "tcgen05": "hw-tcgen05-mma",
            "tmem": "hw-tmem",
            "tma": "hw-tma",
            "mbarrier": "hw-mbarrier",
            "2sm-cooperative": "hw-2sm-cooperative",
            "pdl": "hw-pdl-gdc",
            "nvfp4": "hw-nvfp4",
        }.get(feature)
        if candidate and candidate not in result:
            result.append(candidate)
    return result


def union_values(records: list[dict], field: str) -> list[str]:
    values = []
    for record in records:
        for value in record["parsed"].get(field) or []:
            if value not in values:
                values.append(value)
    return values


def family_correctness_status(records: list[dict]) -> str:
    statuses = list(dict.fromkeys(record["parsed"]["correctness_status"] for record in records))
    return statuses[0] if len(statuses) == 1 else "mixed"


def family_performance_claims(records: list[dict], source_id: str) -> list[dict]:
    claims = []
    for record in records:
        claims.extend(
            performance_claims(
                record["parsed"],
                source_id,
                record["artifact_dir"],
                record["experiment_id"],
            )
        )
    return claims


def family_limitations(records: list[dict]) -> list[str]:
    limitations = [
        "This family page aggregates distinct experiments; results must not be treated as one benchmark run.",
        "Complete code, diffs, measurements, and receipts remain isolated in per-experiment artifact bundles.",
        "Causal mechanisms are hypotheses unless explicitly attributed by the retained evidence.",
    ]
    if any(record["parsed"]["correctness_status"] == "gate-described-no-explicit-result" for record in records):
        limitations.append(
            "At least one retained experiment documents its correctness gate without a separate explicit result."
        )
    return limitations


def family_source_page(family: str, records: list[dict]) -> str:
    records = sorted(records, key=lambda record: record["experiment_id"])
    source_id, _wiki_id = family_page_ids(family)
    artifact_dir = f"artifacts/experiments/{family}"
    techniques = union_values(records, "techniques")
    kernel_types = union_values(records, "kernel_types")
    languages = union_values(records, "languages")
    hardware = union_values(records, "hardware_features")
    tags = list(dict.fromkeys(kernel_types + languages + techniques + hardware))
    limitations = family_limitations(records)
    experiment_rows = []
    for record in records:
        parsed = record["parsed"]
        experiment_rows.append(
            {
                "experiment_id": record["experiment_id"],
                "logical_run_id": record["logical_run_id"],
                "selected_code_path": parsed["logical_code_name"],
                "evidence_sha256": parsed["evidence_sha256"],
                "manifest_row_sha256": record["manifest_sha"],
                "artifact_dir": record["artifact_dir"],
                "correctness_status": parsed["correctness_status"],
                "evidence_limitations": record["limitations"],
            }
        )
    fm = {
        "id": source_id,
        "title": f"Optimization trace family: {FAMILY_LABELS[family]}",
        "source_category": "optimization-trace",
        "task_family": family,
        "architectures": union_values(records, "architectures"),
        "tags": tags,
        "techniques": techniques,
        "hardware_features": hardware,
        "kernel_types": kernel_types,
        "languages": languages,
        "captured_at": "unknown",
        "artifact_dir": artifact_dir,
        "experiment_count": len(records),
        "experiments": experiment_rows,
        "performance_claims": family_performance_claims(records, source_id),
        "correctness_status": family_correctness_status(records),
        "evidence_limitations": limitations,
    }
    lines = [
        f"# {fm['title']}",
        "",
        f"This page groups {len(records)} independently receipted `{family}` optimization experiment(s).",
        "Each bundle remains self-contained and independently hash-verified.",
        "",
        "## Experiment catalog",
        "",
    ]
    for variant, record in enumerate(records, 1):
        parsed = record["parsed"]
        rel_artifact = "../../" + record["artifact_dir"]
        lines.extend(
            [
                f"### Variant {variant}",
                "",
                f"- Architectures: `{', '.join(parsed['architectures'])}`",
                f"- Languages: `{', '.join(parsed['languages'])}`",
                f"- Correctness: `{parsed['correctness_status']}` — {parsed['correctness_detail']}",
                f"- [Task]({rel_artifact}/TASK.md); "
                f"[before]({rel_artifact}/{parsed['before_name']}); "
                f"[after]({rel_artifact}/{parsed['after_name']}); "
                f"[diff]({rel_artifact}/changes.diff); "
                f"[measurements]({rel_artifact}/performance.md); "
                f"[receipt]({rel_artifact}/PROVENANCE.yaml)",
                "",
            ]
        )
        for index, comparison in enumerate(parsed["comparisons"], 1):
            lines.append(
                f"- [Comparison {index}]({rel_artifact}/performance.md#comparison-{index}): "
                f"{comparison['metric']} improved from {comparison['before_value']} {comparison['unit']} "
                f"to {comparison['after_value']} {comparison['unit']}."
            )
        lines.append("")
    lines.extend(["## Family-level limitations", ""])
    lines.extend(f"- {item}" for item in limitations)
    return frontmatter(fm) + "\n".join(lines) + "\n"


def family_wiki_page(family: str, records: list[dict]) -> str:
    records = sorted(records, key=lambda record: record["experiment_id"])
    source_id, wiki_id = family_page_ids(family)
    artifact_dir = f"artifacts/experiments/{family}"
    techniques = union_values(records, "techniques")
    kernel_types = union_values(records, "kernel_types")
    languages = union_values(records, "languages")
    hardware = union_values(records, "hardware_features")
    tags = list(dict.fromkeys(kernel_types + languages + techniques + hardware))
    related = []
    for record in records:
        for value in related_ids(record["parsed"]):
            if value not in related:
                related.append(value)
    limitations = family_limitations(records)
    fm = {
        "id": wiki_id,
        "title": f"Optimization case studies: {FAMILY_LABELS[family]}",
        "type": "kernel",
        "task_family": family,
        "architectures": union_values(records, "architectures"),
        "tags": tags,
        "confidence": "experimental",
        "reproducibility": "snippet",
        "kernel_types": kernel_types,
        "languages": languages,
        "related": related,
        "sources": [source_id],
        "artifact_dir": artifact_dir,
        "experiment_count": len(records),
        "performance_claims": family_performance_claims(records, source_id),
        "correctness_status": family_correctness_status(records),
        "evidence_limitations": limitations,
    }
    source_rel = f"../../sources/experiments/{family}.md"
    lines = [
        f"# {fm['title']}",
        "",
        "## Family overview",
        "",
        f"This page summarizes {len(records)} distinct `{family}` optimization experiment(s). "
        f"The [family source record]({source_rel}) carries the per-experiment evidence hashes.",
        "",
        "Every retained comparison is directionally positive for its metric. Variants remain separate below "
        "because they may target different architectures, workloads, or implementations.",
        "",
        "## Variants and measured improvements",
        "",
    ]
    for variant, record in enumerate(records, 1):
        parsed = record["parsed"]
        rel_artifact = "../../" + record["artifact_dir"]
        lines.extend(
            [
                f"### Variant {variant}",
                "",
                f"Architectures: `{', '.join(parsed['architectures'])}`. "
                f"Languages: `{', '.join(parsed['languages'])}`. "
                f"Correctness: `{parsed['correctness_status']}`.",
                "",
            ]
        )
        for index, comparison in enumerate(parsed["comparisons"], 1):
            lines.append(
                f"- [{comparison['metric'].title()} comparison {index}]"
                f"({rel_artifact}/performance.md#comparison-{index}): "
                f"{comparison['before_value']} {comparison['unit']} before and "
                f"{comparison['after_value']} {comparison['unit']} after."
            )
        lines.extend(
            [
                "",
                f"Complete local evidence: [task]({rel_artifact}/TASK.md), "
                f"[before code]({rel_artifact}/{parsed['before_name']}), "
                f"[after code]({rel_artifact}/{parsed['after_name']}), "
                f"[unified diff]({rel_artifact}/changes.diff), and "
                f"[provenance]({rel_artifact}/PROVENANCE.yaml).",
                "",
                "Observed changes:",
                "",
            ]
        )
        if parsed["observed_changes"]:
            lines.extend(f"- {item}" for item in parsed["observed_changes"])
        else:
            lines.append("- The local unified diff is the authoritative observed change record.")
        hypotheses = ", ".join(parsed["techniques"]) if parsed["techniques"] else "the observed changes"
        lines.extend(
            [
                "",
                f"Possible mechanism: {hypotheses}. This is an evidence-bounded hypothesis, not measured causality.",
                "",
            ]
        )
    lines.extend(["## Applicability and limitations", ""])
    lines.extend(f"- {item}" for item in limitations)
    lines.extend(
        [
            "- These bundles support evidence review; they do not include the original benchmark runtime for an independent rerun.",
            "",
        ]
    )
    return frontmatter(fm) + "\n".join(lines)


def bundle_files(
    row: dict,
    parsed: dict,
    logical_run_id: str,
    source_id: str,
    wiki_id: str,
    manifest_sha: str,
    artifact_dir: str,
    limitations: list[str],
) -> dict[str, bytes]:
    before_name = parsed["before_name"]
    after_name = parsed["after_name"]
    payload_text = {
        "TASK.md": parsed["task"],
        before_name: parsed["before"],
        after_name: parsed["after"],
        "changes.diff": parsed["diff"],
        "performance.md": performance_markdown(parsed),
    }
    payload = {name: value.encode("utf-8") for name, value in payload_text.items()}
    roles = {
        "TASK.md": ("task", "generated"),
        before_name: ("before-code", parsed["evidence_mode"]),
        after_name: ("after-code", parsed["evidence_mode"]),
        "changes.diff": ("unified-diff", "generated"),
        "performance.md": ("performance", "generated"),
    }
    file_rows = []
    for name in sorted(payload):
        role, mode = roles[name]
        entry = {
            "local_path": name,
            "role": role,
            "mode": mode,
            "size": len(payload[name]),
            "sha256": sha256_bytes(payload[name]),
        }
        if name in {before_name, after_name}:
            entry["normalization"] = parsed["evidence_mode"]
        file_rows.append(entry)
    provenance = {
        "source_kind": "optimization-trace",
        "logical_run_id": logical_run_id,
        "imported_evidence_sha256": parsed["evidence_sha256"],
        "imported_manifest_row_sha256": manifest_sha,
        "receipt_date": "unknown",
        "receipt_date_policy": RECEIPT_DATE_POLICY,
        "evidence_limitations": limitations,
        "files": file_rows,
    }
    payload["PROVENANCE.yaml"] = yaml_text(provenance).encode("utf-8")
    return {f"{artifact_dir}/{name}": content for name, content in payload.items()}


def safe_evidence_path(root: Path, raw_path: object) -> Path:
    if not isinstance(raw_path, str) or not raw_path:
        raise ImportFailure("manifest evidence_path must be a non-empty string")
    logical = PurePosixPath(raw_path)
    if logical.is_absolute() or ".." in logical.parts:
        raise ImportFailure("manifest evidence_path must be a contained relative path")
    candidate = root.joinpath(*logical.parts)
    try:
        resolved = candidate.resolve(strict=True)
    except OSError as exc:
        raise ImportFailure("manifest evidence file is missing or unreadable") from exc
    if root != resolved and root not in resolved.parents:
        raise ImportFailure("manifest evidence path escapes the input root")
    if not resolved.is_file():
        raise ImportFailure("manifest evidence path is not a regular file")
    return resolved


def build_import(input_root: Path, repo_root: Path = REPO_ROOT) -> tuple[dict[str, bytes], list[dict], dict]:
    input_root = input_root.resolve(strict=True)
    repo_root = repo_root.resolve(strict=True)
    if input_root == repo_root or repo_root in input_root.parents or input_root in repo_root.parents:
        raise ImportFailure("input root and KernelWiki root must be separate trees")
    index_path = input_root / "index.jsonl"
    if not index_path.is_file():
        raise ImportFailure("input root does not contain a readable index.jsonl")
    index_raw = index_path.read_bytes()
    rows = []
    for number, line in enumerate(index_raw.decode("utf-8").splitlines(), 1):
        try:
            row = json.loads(line)
        except json.JSONDecodeError as exc:
            raise ImportFailure(f"index.jsonl line {number} is invalid JSON") from exc
        if not isinstance(row, dict):
            raise ImportFailure(f"index.jsonl line {number} is not an object")
        rows.append(row)

    artifacts: dict[str, bytes] = {}
    ledger = []
    input_snapshots: dict[Path, str] = {index_path: sha256_bytes(index_raw)}
    exact_targets: dict[tuple[str, str, str], dict] = {}
    semantic_targets: defaultdict[tuple[str, str], list[str]] = defaultdict(list)
    accepted_rows = []
    family_records: defaultdict[str, list[dict]] = defaultdict(list)
    manifest_occurrences = Counter()

    for ordinal, row in enumerate(rows, 1):
        manifest_json = canonical_json(row)
        manifest_sha = sha256_bytes(manifest_json.encode("utf-8"))
        occurrence = manifest_occurrences[manifest_sha]
        manifest_occurrences[manifest_sha] += 1
        input_identity = sha256_bytes(f"{manifest_json}\0{occurrence}".encode("utf-8"))
        input_id = f"trace-input-{input_identity[:20]}"
        base_ledger = {
            "input_id": input_id,
            "manifest_row_sha256": manifest_sha,
            "task_family": row.get("task_family", "unknown"),
        }
        if row.get("status") != "verified_faster":
            ledger.append({**base_ledger, "input_evidence_sha256": None, "disposition": "rejected", "reason_code": "status_not_verified_faster"})
            continue
        try:
            evidence_path = safe_evidence_path(input_root, row.get("evidence_path"))
            raw = evidence_path.read_bytes()
        except (ImportFailure, OSError):
            ledger.append({**base_ledger, "input_evidence_sha256": None, "disposition": "rejected", "reason_code": "evidence_file_unavailable"})
            continue
        input_snapshots[evidence_path] = sha256_bytes(raw)
        normalized, _ = normalized_text(raw)
        evidence_sha = sha256_bytes(normalized.encode("utf-8"))
        parsed, reason = parse_evidence(row, raw)
        if reason:
            ledger.append(
                {
                    **base_ledger,
                    "input_evidence_sha256": evidence_sha,
                    "disposition": "rejected",
                    "reason_code": reason,
                }
            )
            continue
        assert parsed is not None
        exact_key = (
            parsed["evidence_sha256"],
            sha256_bytes(parsed["before"].encode("utf-8")),
            sha256_bytes(parsed["after"].encode("utf-8")),
        )
        if exact_key in exact_targets:
            target = exact_targets[exact_key]
            ledger.append(
                {
                    **base_ledger,
                    "input_evidence_sha256": evidence_sha,
                    "disposition": "duplicate",
                    "reason_code": "exact_evidence_and_code_duplicate",
                    "canonical_input_id": target["input_id"],
                    "canonical_source_id": target["source_id"],
                    "canonical_wiki_id": target["wiki_id"],
                    "canonical_experiment_id": target["experiment_id"],
                    "canonical_artifact_path": target["artifact_path"],
                }
            )
            continue

        family = row["task_family"]
        logical_run_id, experiment_id = logical_ids(row, parsed, manifest_sha)
        source_id, wiki_id = family_page_ids(family)
        artifact_dir = f"artifacts/experiments/{family}/{experiment_id}"
        limitations = evidence_limitations(row, parsed)
        semantic_key = (family, sha256_bytes(parsed["after"].encode("utf-8")))
        semantic_duplicates = list(semantic_targets[semantic_key])
        semantic_targets[semantic_key].append(experiment_id)
        entry = {
            **base_ledger,
            "input_evidence_sha256": evidence_sha,
            "disposition": "accepted",
            "reason_code": "accepted_verified_pair",
            "experiment_id": experiment_id,
            "source_id": source_id,
            "wiki_id": wiki_id,
            "artifact_path": artifact_dir,
        }
        if semantic_duplicates:
            entry["semantic_duplicate_candidates"] = semantic_duplicates
        ledger.append(entry)
        exact_targets[exact_key] = {
            "input_id": input_id,
            "source_id": source_id,
            "wiki_id": wiki_id,
            "experiment_id": experiment_id,
            "artifact_path": artifact_dir,
        }
        artifacts.update(bundle_files(row, parsed, logical_run_id, source_id, wiki_id, manifest_sha, artifact_dir, limitations))
        record = {
            "row": row,
            "parsed": parsed,
            "logical_run_id": logical_run_id,
            "experiment_id": experiment_id,
            "manifest_sha": manifest_sha,
            "artifact_dir": artifact_dir,
            "limitations": limitations,
        }
        family_records[family].append(record)
        accepted_rows.append(record)

    for family, records in sorted(family_records.items()):
        slug = family.replace("_", "-")
        artifacts[f"sources/experiments/{family}.md"] = family_source_page(
            family, records
        ).encode("utf-8")
        artifacts[f"wiki/kernels/kernel-trace-{slug}.md"] = family_wiki_page(
            family, records
        ).encode("utf-8")

    ledger.sort(key=lambda item: item["input_id"])
    artifacts[str(LEDGER_PATH)] = (
        "".join(json.dumps(item, ensure_ascii=False, sort_keys=True) + "\n" for item in ledger)
    ).encode("utf-8")

    # Re-read every authoritative input before permitting a write phase.
    for path, digest in input_snapshots.items():
        if sha256_bytes(path.read_bytes()) != digest:
            raise ImportFailure("input changed while the import was being prepared")

    dispositions = Counter(item["disposition"] for item in ledger)
    reasons = Counter(item["reason_code"] for item in ledger)
    families = defaultdict(Counter)
    architectures = Counter()
    languages = Counter()
    techniques = Counter()
    for item in ledger:
        families[item["task_family"]][item["disposition"]] += 1
    for record in accepted_rows:
        parsed = record["parsed"]
        architectures.update(parsed["architectures"])
        languages.update(parsed["languages"])
        techniques.update(parsed["techniques"])
    summary = {
        "total_rows": len(rows),
        "dispositions": dict(sorted(dispositions.items())),
        "reasons": dict(sorted(reasons.items())),
        "families": {key: dict(sorted(value.items())) for key, value in sorted(families.items())},
        "architectures": dict(sorted(architectures.items())),
        "languages": dict(sorted(languages.items())),
        "techniques": dict(sorted(techniques.items())),
        "generated_files": len(artifacts),
    }
    return artifacts, ledger, summary


def importer_owned_files(repo_root: Path) -> set[Path]:
    owned = set()
    source_root = repo_root / "sources" / "experiments"
    if source_root.is_dir():
        owned.update(path for path in source_root.rglob("*.md") if path.is_file() or path.is_symlink())
    wiki_root = repo_root / "wiki" / "kernels"
    if wiki_root.is_dir():
        owned.update(path for path in wiki_root.glob("kernel-trace-*.md") if path.is_file() or path.is_symlink())
    artifact_root = repo_root / "artifacts" / "experiments"
    if artifact_root.is_dir():
        owned.update(path for path in artifact_root.rglob("*") if path.is_file() or path.is_symlink())
    return owned


def write_atomic(repo_root: Path, artifacts: dict[str, bytes], force: bool) -> tuple[int, int, int]:
    repo_root = repo_root.resolve(strict=True)
    changed = 0
    unchanged = 0
    conflicts = []
    expected_paths = {(repo_root / rel).resolve() for rel in artifacts}
    stale = sorted(importer_owned_files(repo_root) - expected_paths)
    if stale and not force:
        conflicts.extend(
            f"{path.relative_to(repo_root)} is stale importer-owned output (use --force)"
            for path in stale
        )
    for rel, content in sorted(artifacts.items()):
        target = repo_root / rel
        if target.exists():
            if not target.is_file():
                conflicts.append(f"{rel} exists and is not a file")
            elif target.read_bytes() == content:
                unchanged += 1
            elif not force:
                conflicts.append(f"{rel} exists with different content (use --force)")
    if conflicts:
        raise ImportFailure("\n".join(conflicts))

    stage = Path(tempfile.mkdtemp(prefix=".trace-import-stage-", dir=repo_root))
    try:
        for rel, content in sorted(artifacts.items()):
            staged = stage / rel
            staged.parent.mkdir(parents=True, exist_ok=True)
            staged.write_bytes(content)
        for rel, content in sorted(artifacts.items()):
            target = repo_root / rel
            if target.is_file() and target.read_bytes() == content:
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            staged = stage / rel
            temporary = target.with_name(f".{target.name}.import-{os.getpid()}")
            shutil.copyfile(staged, temporary)
            os.replace(temporary, target)
            changed += 1
    finally:
        shutil.rmtree(stage, ignore_errors=True)
    removed = 0
    if force:
        for path in stale:
            if path.is_file() or path.is_symlink():
                path.unlink()
                removed += 1
        for root_name in ("sources/experiments", "artifacts/experiments"):
            root = repo_root / root_name
            if root.is_dir():
                for directory in sorted((path for path in root.rglob("*") if path.is_dir()), reverse=True):
                    try:
                        directory.rmdir()
                    except OSError:
                        pass
    return changed, unchanged, removed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--input-root", required=True, type=Path, help="Read-only trace evidence root")
    parser.add_argument("--dry-run", action="store_true", help="Validate and report dispositions without writing")
    parser.add_argument("--force", action="store_true", help="Replace importer-owned files whose bytes differ")
    args = parser.parse_args()
    try:
        artifacts, _ledger, summary = build_import(args.input_root, REPO_ROOT)
        print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))
        if args.dry_run:
            print("Dry run: no files written.")
            return 0
        changed, unchanged, removed = write_atomic(REPO_ROOT, artifacts, args.force)
        print(
            f"Import complete: {changed} file(s) written, {unchanged} already byte-identical, "
            f"{removed} stale importer-owned file(s) removed."
        )
        return 0
    except (ImportFailure, OSError, UnicodeDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
